iiitv/getmein-web

.gitignore
package-lock.json
public/client.js
views/index.html

Fixes Issue #3 
**Changes**
- Fixed the instant username check
- Added .gitignore
**Screenshot for the change**

Bug fix - instant username check

---

README.md
createmail.js
package-lock.json
package.json
public/client.js
server.js

This is a PR for the issue #6 
Tasks completed : 
- Created a route which takes the username and the email ID as the parameters, encrypts them and sends an activation link to the user's email ID.
- Created a route that handles the activation link, and verifies if the link is correct or not.
- Make the form work with this route.
- After verification, adds the member to the respective link

[WIP] Nodemailer integration

---

public/client.js
public/style.css
views/index.html

Fixes #10 
Changes - Invalid username message is now not shown on hovering. Bug fixed

Invalid username always visible on hover is fixed

---

.gitignore
package-lock.json
package.json
views/index.html

Changed meta tag, added email instructions and updated gitignore 😢

Added email instructions and changed meta tag

---

.github/PULL_REQUEST_TEMPLATE.md

Created a PR template
Fixes #21

Created pull request template

---

server.js

Fixes #{ISSUE NUMBER}
_just code improvement_

removed pass its not needed

---

README.md

Fixes #43 
Previously, the image of Facebook Link was broken. This PR adds links to other Social Media acocunts and email of the organisation with their icons.

Add icons and links in README

---

README.md
server.js

Fixes #55 
Defined variable to read values

read transport config from env

---

.eslintrc.js
createmail.js
package-lock.json
package.json
public/client.js
server.js

Fixes #61 
- Add ESLint with basic plugins like single quotes, line length, and const and let checks as suggested by @yashLadha and @aashutoshrathi 
- Removed semistandard and snazzy from dependencies as they were not used after adding eslint
- Add pretest before push

Add ESLint

---

.eslintrc.js
CODE_OF_CONDUCT.md
README.md
createmail.js
package-lock.json
package.json
public/client.js
views/index.html

This PR addresses a few smaller issues:
- Fixes build ✅ 
- Fixes Security Warnings due to jQuery. 🔐 
- Add UIKit package to suppress its errors. ➕ 
- Changes `Github` to `GitHub` 😅

Mass Cleanup

---

server.js

Invite to Slack

---

.gitignore
CONTRIBUTING.md
README.md

- Added Travis, Issue, and License badge to README in for-the-badge style.
- Also removed Code Style - semistandard badge as code style does not follows semistandard now.

Add Travis, Issue, and License badge to README

---

README.md

 ⚡️ Add Stargazers graph

---

public/style.css
views/index.html

Fixed footer ✔

---

public/style.css
views/index.html

Revert "Fixed footer ✔"

---

README.md

Add instructions to join Gitter Channel, Member, Batch and Outsider Teams in IIITV Org and instructions to start contributing.

Add instruction in README under How to Use

---

public/style.css
views/index.html

Fixes  #78    #81 
With solution of #78 which was done in PR #80 .
Now added fix for #81 too.

Small screen view with scroll feature 😄

---

public/client.js

Fixes #74 
The Validate email function is implemented.
- Bug fix (non-breaking change which fixes an issue)

Email function validated

---

views/index.html

Added Preload in css files
used defer to load fast script
Fixes #93

Add Preload

---

server.js

Fixes #95 
Auto updating Glitch using glitch webhook
I have used this blog for fixing issue - https://dev.to/healeycodes/continuous-deployment-to-glitch-via-github-webhooks-3hmh

Auto-update Glitch with GitHub

---

README.md
constants.js
createmail.js
package-lock.json
package.json
server.js

Add Sendgrid

---

constants.js
server.js
shrinkwrap.yaml

Some quickfixes

---

server.js

Fixes #107 
Update API call as per constant reminder mail from GitHub :octocat:

fix: Use Auth Header instead of URL param

---

constants.js
package-lock.json
server.js

Fixes #116 
Removing dependency of org_id and team_id using new v3 API.

fix: moved to API 3 github

---

public/client.js

✨ greet message enhancement

---

public/darkmode.js
public/dist/darkmode.dev.js
public/style.css
views/index.html

Fixes #85 
The font in the textbox, when toggling the website from Black Theme to the white theme, should be visible

Toggling Issue in Dark/Light themes 

---

package-lock.json
package.json
public/client.js
public/dist/darkmode.dev.js

Fixes #127 
CORS added and bug fixed.

cors issues fixed and state username color bug fixed

---

createmail.js
package-lock.json
package.json

Add discord invites in mail

---

constants.js
package-lock.json
public/client.js
server.js

Fixed the bug because of which mail weren't being send to the users and removed slack feature

:pencil2: fixed get me in mail sending feature and updated tokens

---

README.md
constants.js
package-lock.json
package.json
public/client.js
server.js

- Fix sendmail api endpoint.
- Replace sendgrid with gmail smtp.

Fix sendmail api 
